name: Continuous Integration (Lambda)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy to lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: List files (for debugging)
        run: ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Note: Kept for reference; This offers a more customizable way to package the Lambda function.
      #       Unfortunately, there does not seem to be a way to expose the resulting zip file as an artifact.
      #       Using `actions/upload-artifact` to package this zip file will result a nested zip file (zip file of zip file) result.
      #       So, we are using `actions/upload-artifact` to package the source files instead.
      # - name: Packaging Lambda Function
      #   run: |
      #     $publish_file_path = '${{ vars.LAMBDA_ZIP_FILE_PATH }}'
      #     [string[]]$file_list = Get-ChildItem ${{ vars.LAMBDA_SRC_FILE_PATH }}
      #     $archive_specs = @{
      #       Path = $file_list
      #       DestinationPath = $publish_file_path
      #     }
      #     Compress-Archive @archive_specs -Force

      - name: Create AWS Lambda Function Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-lambda-package                # Name of the artifact (aws-lambda-package.zip)
          path: |                                 # Note: Use unix style path (./). Does not work with Windows style path (.\).
            ${{ vars.LAMBDA_SRC_FILE_PATH }}  
          
      # *Pukes* -- Let's see if this works
      - name: Download AWS Lambda Function Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: aws-lambda-package
          path: ./publish

      - name: List files (for debugging)
        run: ls -R


      # - name: Deploy Lambda Function
      #   uses: aws-actions/aws-lambda-deploy@v1
      #   with:
      #     function-name: my-lambda-function
      #     code-artifacts-dir: ./dist

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
